export const data = [
    {
        question: "What bird makes the vocalization <i>Caw, caw</i>?",
        option1: "American Crow",
        option2: "Common Raven",
        option3: "American Robin",
        option4: "Woodhouse's Scrub-Jay",
        ans: 1,
    },
    {
        question: "What bird produces a series of low, whistled phrases?",
        option1: "Townsend's Solitaire",
        option2: "House Finch",
        option3: "House Sparrow",
        option4: "American Robin",
        ans: 4,
    },
    {
        question: "Which bird vocalizes with <i>fillp, fillp</i>?",
        option1: "House Finch",
        option2: "House Sparrow",
        option3: "White-crowned Sparrow",
        option4: "Spotted Towhee",
        ans: 1,
    },
    {
        question: "What bird makes a muffled, dry buzzing <i>wrrsh</i> sound?",
        option1: "Red-winged Blackbird",
        option2: "Cedar Waxwing",
        option3: "European Starling",
        option4: "Dark-eyed Junco",
        ans: 3,
    },
    {
        question: "Which bird produces a monotonous series of nearly identical chirps?",
        option1: "Black-capped Chickadee",
        option2: "House Finch",
        option3: "European Starling",
        option4: "House Sparrow",
        ans: 4,
    },
];
